name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  id-token: write  # Requerido para deploy-pages
  contents: write  # Permiso para escribir en el repositorio

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./out

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy  # Asegura que el despliegue solo ocurra después de la construcción

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
